name: Drift
options:
  bundleIdPrefix: com.drift
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    ENABLE_PREVIEWS: YES
    CURRENT_PROJECT_VERSION: 6
    MARKETING_VERSION: "0.2"
    APP_DISPLAY_NAME: Drift
    PRODUCT_BUNDLE_IDENTIFIER: com.drift.notes
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    DEVELOPMENT_TEAM: 7DGN24C3GR
    CODE_SIGN_STYLE: Automatic

targets:
  Drift:
    type: application
    platform: iOS
    sources:
      - path: Drift
        excludes:
          - "Info.plist"
    settings:
      base:
        PRODUCT_NAME: Drift
        INFOPLIST_FILE: Drift/Info.plist
        GENERATE_INFOPLIST_FILE: NO

  DriftTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DriftTests
    dependencies:
      - target: Drift
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.drift.notes.tests

  DriftUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: DriftUITests
    dependencies:
      - target: Drift
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.drift.notes.uitests
        TEST_TARGET_NAME: Drift
