#!/bin/bash
set -euo pipefail
repo_dir="$(cd "$(dirname "$0")/.." && pwd)"
output_dir="$repo_dir/dist/site"
rm -rf "$output_dir"
mkdir -p "$output_dir/assets"
node "$repo_dir/scripts/site/build-page.mjs"
cp "$repo_dir/docs/site/robots.txt" "$output_dir/robots.txt"
cp "$repo_dir/docs/site/sitemap.xml" "$output_dir/sitemap.xml"
cp "$repo_dir/docs/site/assets/desktop-demo.jpg" "$output_dir/assets/desktop-demo.jpg"
cp "$repo_dir/docs/site/assets/desktop-demo-first-frame.mp4" "$output_dir/assets/desktop-demo-first-frame.mp4"
cp "$repo_dir/docs/site/assets/iphone-800.webp" "$output_dir/assets/iphone-800.webp"
cp "$repo_dir/docs/site/assets/iphone-1200.webp" "$output_dir/assets/iphone-1200.webp"
cp "$repo_dir/docs/site/assets/chris.jpg" "$output_dir/assets/chris.jpg"
cp "$repo_dir/docs/site/assets/social-preview.png" "$output_dir/assets/social-preview.png"
cp "$repo_dir/docs/site/assets/social-preview-desktop-dark.png" "$output_dir/assets/social-preview-desktop-dark.png"
cp "$repo_dir/docs/site/assets/apple-touch-icon.png" "$output_dir/assets/apple-touch-icon.png"
cp "$repo_dir/docs/assets/demo.mp4" "$output_dir/assets/desktop-demo.mp4"
cp "$repo_dir/docs/assets/iphone.png" "$output_dir/assets/iphone.png"
cp "$repo_dir/drift-mac/public/fonts/Newsreader-Italic.ttf" "$output_dir/assets/Newsreader-Italic.ttf"
cp "$repo_dir/drift-mac/public/fonts/OFL.txt" "$output_dir/assets/Newsreader-OFL.txt"
cp "$repo_dir/drift-mac/src-tauri/icons/icon.png" "$output_dir/assets/favicon.png"
touch "$output_dir/.nojekyll"
echo "Built landing page: $output_dir"
